version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - mvn package && mv target/*.war ROOT.war
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - mvn package
artifacts:
  files:
    'ROOT.war'