Use [TriceraDB]
GO

-- Core Tables
SELECT * FROM RESPONSE
SELECT * FROM REQUEST
SELECT * FROM RESPONSE_TYPE

-- Summary Tables
SELECT * FROM SUMMARY_CI

-- Record tables
SELECT * FROM SAMPLE_LESSONLEARNT
SELECT * FROM SAMPLE_3C
SELECT * FROM DOCUMENTS

/***** DELETE (WARNING!) *****
DELETE FROM RESPONSE 
	WHERE parent_reqid = 10
DELETE FROM SUMMARY_CI
DELETE FROM SAMPLE_LESSONLEARNT
DELETE FROM SAMPLE_3C
DELETE FROM DOCUMENTS

******************************/

-- Pre-populated tables for Graphic Samples
SELECT * FROM EMPLOYEE
SELECT * FROM LEAVE_CREDITS


-- Display a vertical bar graph of employee leave credits
SELECT E.NICK_NAME, LC.LEAVE_CREDITS FROM EMPLOYEE E INNER JOIN LEAVE_CREDITS LC ON E.EMP_ID = LC.EMP_ID

